### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by pravic** [MISoftware/OmniLite#1]
Just tried to open a _sciter-sdk/samples/basics/test-inputs.htm_ file.

Stacktrace:

>    в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   в System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   в System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   в System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   в SciterSharp.SciterEventHandler.OnScriptCall(SciterElement se, String name, SciterValue[] args, SciterValue& result)
   в SciterSharp.SciterEventHandler.EventProc(IntPtr tag, IntPtr he, UInt32 evtg, IntPtr prms)
   в SciterSharp.Interop.PInvokeWindows.DispatchMessage(MSG& lpmsg)
   в SciterSharp.Interop.PInvokeUtils.RunMsgLoop()
   в OmniLite.Program.Main(String[] args)

**Comment by midiway** [comment]
No problem here..
![](https://i.imgur.com/tV85FMk.png)

You donwloaded the binaries or compiled from source?
Try from sources..

**Comment by pravic** [comment]
Downloaded.

**Comment by midiway** [comment]
Well, I won't have a chance to solve it if you don't provide me more info...
You should download the sources, open the .sln, hit F5, load the .html again, and when it break on the exception, go to Debug -> Save Dump As.. -> Select Minidump (.dmp) to get a small dump file..
