### ISSUE TITLE
Reload file opens an editor, Edit file does nothing

### ISSUE THREAD

**Issue by pravic** [MISoftware/OmniLite#3]
Subj. "Open containing folder" even resists to be pressed (like an exception in event handler).

Reload file, press Network -> app is silently closed.

And it used to be a paid app? Really?

**Comment by midiway** [comment]
I had to do a major rewrite for it to work in OSX, so new bugs were introduced.
Hope they are fixed now.
Download test it plz.
http://misoftware.com.br/Download/OmniLiteWindows
